repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/TekWizely/pre-commit-golang
    rev: v0.8.3
    hooks:
      - id: go-imports
      - id: go-test-repo-mod
